#1-Definition of Networks
networks:
  data_pulse_net:
    driver: bridge

#2-Definition of Volumes
volumes:
  airflow-dags:
  airflow-logs:
  airflow-plugins:
  airflow-postgres-data:
  spark-data:
  grafana-storage: 

#3-Definition of Services
services:

  #### Kafka's Services ####
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    networks:
      - data_pulse_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    networks:
      - data_pulse_net
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  ##### Spark Services #####
  spark-master:
    #THE CORRECT AND OFFICIAL IMAGE
    image: apache/spark:3.5.1-python3
    container_name: spark-master
    user: root
    networks:
      - data_pulse_net
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark/app:/opt/spark/work-dir/app
      - ./spark/data:/opt/spark/work-dir/data
    #THE CORRECT COMMAND TO KEEP THE MASTER ON
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: apache/spark:3.5.1-python3
    container_name: spark-worker
    user: root
    networks:
      - data_pulse_net
    depends_on:
      - spark-master
    volumes:
      - ./spark/app:/opt/spark/work-dir/app
      - ./spark/data:/opt/spark/work-dir/data
    #THE CORRECT COMMAND TO KEEP THE WORKER ON
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  ##### Airflow Services #####
  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - data_pulse_net
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.9.2
    container_name: airflow-init
    depends_on:
      - postgres
    networks:
      - data_pulse_net
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: >
      bash -c "
        airflow db init &&
        airflow users create --role Admin --username admin --email admin@example.org --firstname Admin --lastname User --password admin
      "

  airflow-webserver:
    image: apache/airflow:2.9.2
    container_name: airflow-webserver
    user: root
    depends_on:
      - airflow-init
    networks:
      - data_pulse_net
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - //./pipe/docker_engine:/var/run/docker.sock
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: airflow-scheduler
    user: root
    depends_on:
      - airflow-init
    networks:
      - data_pulse_net
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - //./pipe/docker_engine:/var/run/docker.sock
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: airflow scheduler

